global:
  scrape_interval: 5s  # How often to scrape targets

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9999']  # Adjust if needed